### ISSUE TITLE
Limit docker log size

### ISSUE THREAD

**Issue by voroyam** [owncloud/appliance#45]
After our customer had the stoppage of service because of lack of storage again, we need to implement a logging limitation on the docker container logs.

here is what I found.

@tboerger what do you think?

---------

https://stackoverflow.com/questions/33017329/where-is-a-log-file-with-logs-from-a-container

-----------

Docker 1.8 and docker-compose 1.4 there is already exists a method to limit log size using docker compose log driver and log-opt max-size:

```
mycontainer:
  ...
  log_driver: "json-file"
  log_opt:
    # limit logs to 2MB (20 rotations of 100K each)
    max-size: "100k"
    max-file: "20"
```

----------

In docker compose files of version '2' , the syntax changed a bit:

```
version: '2'
...
mycontainer:
  ...
  logging:
    #limit logs to 200MB (4rotations of 50M each)
    driver: "json-file"
    options:
      max-size: "50m"
      max-file: "4"
```
