### ISSUE TITLE
OpenID Connect Android App redirect broken

### ISSUE THREAD

**Issue by voroyam** [owncloud/appliance#97]
When trying to connect to our test server with the android app 2.1.7 one get's redirected to the default login screen. After entering the credentials the in App browser stays open.

Test Server is still the same:
```
https://ucsd.owncloud.works

Administrator
ownCloud_1234
```

@michaelstingl 
@edamrose 

here is the mitm proxy log with requests and responses

https://cloud.owncloud.com/index.php/s/MrVl1eRrjDOocae

We saw a 302 response on the login request and then all the info from the OIDC got lost and we got redirected to the default login screen.

![image](https://user-images.githubusercontent.com/24212810/114677400-8fa32680-9d0a-11eb-8534-2005aebc3404.png)

```
  - id: e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
    secret: dInFYGV33xKzhbRmpqQltYNdfLdJIfJ9L5ISoKhNoT9qZftpdWSP71VrpGR9pmoD
    name: ownCloud Android app
    application_type: native
    redirect_uris:
      - oc://android.owncloud.com
```

GET Request:
```
GET https://ucsd.owncloud.works/owncloud/
index.php/apps/oauth2/authorize?
redirect_uri=oc%3A%2F%2Fandroid.owncloud.com&
client_id=e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD&
response_type=code&scope= HTTP/1.1
```

![image](https://user-images.githubusercontent.com/24212810/114677711-db55d000-9d0a-11eb-9a10-52ad6708f5d9.png)

Response:

![image](https://user-images.githubusercontent.com/24212810/114677761-e872bf00-9d0a-11eb-9c0c-9d35702ccd1b.png]

Then we get the default login page:

![image](https://user-images.githubusercontent.com/24212810/114677959-13f5a980-9d0b-11eb-8f90-07f71050e004.png)

Summery of events:

![image](https://user-images.githubusercontent.com/24212810/114678006-1eb03e80-9d0b-11eb-94b6-e70b78356509.png)
